# Generated by Django 4.1.1 on 2022-09-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kota', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'kota',
                'db_table': 'kota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pinjaman', models.IntegerField()),
                ('tenor', models.CharField(max_length=1)),
                ('nama', models.CharField(max_length=60)),
                ('telp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('kota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.kota')),
            ],
            options={
                'verbose_name': 'form',
                'db_table': 'form',
                'managed': True,
            },
        ),
    ]
