# Generated by Django 4.1.1 on 2022-09-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_addtablekotaform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='kota_id',
            field=models.ForeignKey(db_column='kota_id', on_delete=django.db.models.deletion.CASCADE, to='form.kota'),
        ),
    ]
